// examples/vue3/src/App.vue
<template>
  <main class="reset:novout">
    <div
      class="text-test flex:col bg:#CCCCCC h[min 100vh] p[0 0 0 5rem] bg[/vue.png cover] dark(bg:#222222)">
      <section>
        <p
          class="text[roboto primary 4rem 700] shadow[text v-5 h-5 radius-30] p[10rem 0 0 0] md(text:1rem) dark(text[roboto #CCCCCC 4rem 700])">
          Hello UnunuraCSS!</p>
      </section>
    </div>
  </main>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';

const i = ref<boolean>(true)

onMounted(() => {
  setInterval(() => {
    i.value = !i.value
  }, 2000)
})

const onClick = () => {
  window.location.href = 'https://github.com/Novout/ununuracss'
}
</script>

// examples/svelte/src/App.svelte
<main class="reset:novout h[min 100vh] flex[col h-center v-center] w:100% bg:#CCCCCC">
  <p class="text[arial 700 2rem] shadow[text #AC0544 h-5 v-5 blur-40] typo[lspacing-1px]">Hello UnunuraCSS in <span class="text[orange 5rem] hover(text[black 5rem]) tr[delay-100ms duration-0.3s all ease-in] shadow[text none]">Svelte</span></p>
</main>
